title: Streamdata Gallery Google API Discovery Service
url: google-api-discovery-service.streamdata.gallery
tag: Google API Discovery Service
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: google-api-discovery-service
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
